live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#ffffff"
yellow = "#d19a66"

[colors.normal]
black = "#1e2127"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#abb2bf"
yellow = "#d19a66"

[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[cursor.style]
blinking = "On"
shape = "Underline"

[cursor.vi_mode_style]
shape = "Block"

[font]
size = 14

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mode = "~Search"
mods = "Super"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchBackward"
key = "F"
mode = "~Search"
mods = "Control"

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = true

[window]
decorations = "buttonless"
opacity = 0.7

[window.padding]
x = 5
y = 5
