#!/usr/bin/env bash

set -e

log() {
  local green=$(tput setaf 2)
  local reset=$(tput sgr0)
  printf "${green}${1}${reset}\n"
}

# symlink
log "🔗 Creating symlinks..."
stow -v --adopt \
  alacritty \
  brew \
  git \
  karabiner \
  vim \
  vscode \
  zsh
log "🔗 Created symlinks!\n"

# install homebrew and packages
which brew > /dev/null \
  && log "🍺 Homebrew already installed!" \
  || (
    log "🍺 Installing Homebrew..." \
    && /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" \
    && log "🍺 Installed Homebrew!\n"
    && brew bundle --file brew/.config/brew/Brewfile
  )

# install vim plug
log "🔌 Installing Vim plug..."
curl -fLo ./vim/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
log "🔌 Installed Vim plug!\n"
