tap "d12frosted/emacs-plus"
brew "bat"
brew "htop"
brew "jq"
brew "ripgrep"
brew "stow"
brew "tldr"
brew "tree"
brew "d12frosted/emacs-plus/emacs-plus@29", args: ["with-memeplex-slim-icon", "with-native-comp"]
cask "alacritty"
cask "amethyst"
cask "brave-browser"
cask "font-hack-nerd-font"
cask "karabiner-elements"
cask "spotify"
