"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch $git_state $git_status
$cmd_duration
$character
"""

add_newline = false
command_timeout = 1000

[cmd_duration]
format = "[\\(took $duration\\)\n](bold yellow)"
min_time = 500
show_milliseconds = true

[directory]
home_symbol = ""
truncate_to_repo = false

[git_branch]
format = "[{$symbol$branch}]($style)"
only_attached = true
symbol = ""
style = "bold cyan"
ignore_branches = ["main"]
