format = """
$directory\
$git_branch $git_commit $git_state $git_metrics $git_status
$cmd_duration
$character
"""

add_newline = false

[character]
error_symbol = "[>](bold red)"
success_symbol = "[>](bold green)"

[cmd_duration]
format = "[\\(took $duration\\)\n](bold yellow)"
min_time = 500
show_milliseconds = true

[directory]
home_symbol = ""

[git_branch]
format = "[{$symbol$branch}]($style)"
only_attached = true
symbol = ""
style = "bold cyan"
