
# tap repositories and their packages

tap homebrew/core
brew adns
brew antibody
brew autoconf
brew automake
brew bdw-gc
brew cask
brew emacs
brew gdbm
brew gettext
brew git
brew gmp
brew gnupg
brew gnutls
brew go
brew guile
brew htop
brew icu4c
brew jansson
brew libassuan
brew libevent
brew libffi
brew libgcrypt
brew libgpg-error
brew libidn2
brew libksba
brew libtasn1
brew libtool
brew libunistring
brew libusb
brew libyaml
brew lua
brew mas
brew ncurses
brew nettle
brew node
brew npth
brew openssl@1.1
brew p11-kit
brew pcre
brew pcre2
brew perl
brew pinentry
brew pkg-config
brew python@3.8
brew python@3.9
brew readline
brew ripgrep
brew ruby
brew sqlite
brew stow
brew tmux
brew tree
brew unbound
brew utf8proc
brew vim
brew xz
brew yarn
brew zsh
brew zsh-syntax-highlighting

tap homebrew/bundle

tap homebrew/cask-fonts
cask font-hack-nerd-font

tap homebrew/cask-versions

tap homebrew/cask
cask alacritty
cask amethyst
cask docker
cask firefox
cask google-chrome
cask jiggler
cask karabiner-elements
cask mutespotifyads
cask oversight
cask slack
cask spotify
cask visual-studio-code

tap getantibody/tap

tap rcmdnk/file
brew brew-file

tap universal-ctags/universal-ctags
brew universal-ctags --HEAD

# Other Homebrew packages
brew skitch
