-- tab
vim.api.nvim_set_option('expandtab', true)
vim.api.nvim_set_option('smarttab', true)
vim.api.nvim_set_option('shiftwidth', 2)
vim.api.nvim_set_option('tabstop', 2)
-- search
vim.api.nvim_set_option('hlsearch', true)
vim.api.nvim_set_option('incsearch', true)
vim.api.nvim_set_option('ignorecase', true)
vim.api.nvim_set_option('smartcase', true)
-- splits
vim.api.nvim_set_option('splitbelow', true)
vim.api.nvim_set_option('splitright', true)
-- ui
vim.api.nvim_set_option('wrap', false)
vim.api.nvim_set_option('scrolloff', 5)
vim.api.nvim_set_option('termguicolors', true)
vim.api.nvim_set_option('cursorline', true)
vim.api.nvim_set_option('number', true)
vim.api.nvim_set_option('relativenumber', true)
-- miscellaneous
vim.api.nvim_set_option('hidden', true)
vim.api.nvim_set_option('backup', false)
vim.api.nvim_set_option('swapfile', false)
vim.api.nvim_set_option('spell', true)
vim.api.nvim_set_option('fileencoding', 'utf-8')
vim.api.nvim_set_option('mouse', 'a')
vim.api.nvim_set_option('clipboard', 'unnamedplus')
